### ISSUE TITLE
Tests Schémas // Modifications de l'ANSM 

### ISSUE THREAD

**Issue by JulienBarnu** [SocialGouv/covid19-tests-schemas#3]
Voici les demandes de modifications sur la structure par rapport au fichier Excel initial :
- Disponibilité réglementaire : enlever l'option "Autorisation de mise sur le marche en France" 
- Technologie de test : remplacer TROD par "Test rapide" + ajouter "Autotest" 
- Renommer le champ "Indications du test" en "Usages du test" 
- Renommer le champ "Éventuelles complications liées au test" en "Signalements de réactovigilance"
- Ajouter un champ "Distributeurs en France"

**Comment by revolunet** [comment]
corrigé
