### ISSUE TITLE
Tests Schémas // Modifications Bercy

### ISSUE THREAD

**Issue by JulienBarnu** [SocialGouv/covid19-tests-schemas#4]
Hello,
Voici comme promis les modifications issues de notre call de 20h avec Bercy, et donc si tout va bien les dernières du premier sprint (je numérote en fonction des lignes Excel):
- fabricant : remplacer par "producteur"
- ajouter après le champ "distributeur en france" un champ "nationalité du distributeur"
- renommer le champ "pays de fabrication" en "pays de production"
- Supprimer le champ "pays de distribution"
- Dans la liste déroulante "marquage / normes" supprimer "N" et ajouter "Validation CNR" et "Validation ANSM"
- dans "technologie de test" ajouter un choix "Test antigénique" 
- après "technologie de test" ajouter un champ libre "Machines nécessaires" 
- après "Machines nécessaires" ajouter un champ "Test ouvert / fermé" avec trois choix:
1. Ouvert
2. Fermé
3. NC
- dans type de prélèvement nécessaire au test ajouter une liste déroulante:
1. Sérum
2. Plasma
3. Sang
4. Micro-gouttes capillaires
5. Naso-pharyngé
6. Salive
7. Selles
8. Larmes
9. Autres
- supprimer le champ "modalités de prélèvement"
- dans le champ "Modalités d'acheminement des prélèvements" ajouter une liste déroulante
1. Emballage simple
2. Triple emballage
3. Chaîne du froid
4. Autres
- supprimer la mention "par régions" dans le nom du champ "Nombre de structures en mesure de faire le test sur le territoire national"
- Renommer le champ "Délais de réponse au test (en minutes, heures ou jours)" en "Vitesse d'analyse"
- Dans le champ "Facteurs faisant varier VPP/VPN/Se/Sp" supprimer la mention "préciser avec quoi"
- Dans le champ "Fourchette de coûts du test (par test)" remplacer le mot "coûts" par "prix"
- Dans le champ "Nombre de tests disponibles au niveau national (préciser la date pertinente)" supprimer la mention "préciser la date pertinente" et permettre à l'utilisateur de remplir un chiffre pour chaque mois : avril, mai et juin.
- Renommer le champ "Nombre de tests disponibles au niveau international" par un champ "Capacité de production"
- Ajouter après le champ "Autres intérêts du test" un champ "Point de contact"

**Comment by revolunet** [comment]
C'est à jour; Quelques questions :

 - Distributeur France : il ne peut y en avoir qu'un ? (jai mis plusieurs possibles)
 - Capacité de production : du coup j'ai mis un simple champ numérique. il faudrait préciser la période... par semaine, mois ?

Il faudrait qu'on refasse une passe sur les champs qui permettent ou pas la selection multiple. ex : pays de production, dispos réglementaires, normes... certains paramètres sont sûrement exclusifs, d'autres pas.

**Comment by JulienBarnu** [comment]
Merci c’est top !

Pour te répondre : il peut y avoir plusieurs distributeurs mais dans ce cas il faut une fiche par distributeur car ça peut faire varier les autres champs (capacité, confiance dans le distributeur, etc.). Donc c’est bien un champ avec une seule entrée.

Capacité de production : partons sur un chiffre en nombre de tests par semaine !

OK pour les sélections multiples on refait une passe demain avec Ilhem par tel

A+
Julien

**Comment by revolunet** [comment]
Il faudrait aussi établir la liste des champs obligatoires
