### ISSUE TITLE
Base Tests // Champs obligatoires, champs multiples et deux nouveaux champs

### ISSUE THREAD

**Issue by JulienBarnu** [SocialGouv/covid19-tests-schemas#5]
Liste des champs obligatoires
-	Nom du test
-	Statut (champ à ajouter, cf. ci-dessous)
-	Disponibilité réglementaire
-	Technologie de test

Listes des champs qui permettent la sélection multiple
-	Marquage / Normes
-	Modalités d'acheminement des prélèvements
-	Facteurs faisant varier VPP/VPN/Se/Sp
-	Stratégie de canaux de distribution des tests

Rajouter à la fin un champ « Fiche produit » qui permette d’uploader un fichier PDF ou une image

Rajouter après « Pays de production » un champ « Statut » avec la liste déroulante suivante :
1.	Non validé
2.	En cours d’évaluation
3.	Validé
4.	Inconnu

**Comment by revolunet** [comment]
intégré
